---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-mainline
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/nginx-ssl:mainline .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nginx-ssl:mainline
  - docker tag pdr.nephatrine.net/nephatrine/nginx-ssl:mainline nephatrine/nginx-ssl:mainline
  - HOME=/mnt/config/home docker push nephatrine/nginx-ssl:mainline
  - docker rmi pdr.nephatrine.net/nephatrine/nginx-ssl:mainline
- name: build-latest
  commands:
  - docker tag nephatrine/nginx-ssl:mainline pdr.nephatrine.net/nephatrine/nginx-ssl:latest
  - docker build --pull -t pdr.nephatrine.net/nephatrine/nginx-ssl:latest .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nginx-ssl:latest
  - docker tag pdr.nephatrine.net/nephatrine/nginx-ssl:latest nephatrine/nginx-ssl:latest
  - HOME=/mnt/config/home docker push nephatrine/nginx-ssl:latest
  - docker rmi pdr.nephatrine.net/nephatrine/nginx-ssl:latest
  depends_on:
  - build-mainline

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: pipeline
name: propogate

steps:
- name: trigger
  image: plugins/downstream
  settings:
    server: https://ci.nephatrine.net
    token:
      from_secret: drone-auth
    fork: false
    repositories:
      - nephatrine/docker-nginx-php@master

depends_on:
- default

---
kind: signature
hmac: 95d208254438bdda6b78868ef3053f30fc1b2a9ebb3df236a6359577d7e41ae4

...
