---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-1.18
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/nginx-ssl:1.18 -f Dockerfile-1.18 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nginx-ssl:1.18
  - docker tag pdr.nephatrine.net/nephatrine/nginx-ssl:1.18 nephatrine/nginx-ssl:1.18
  - HOME=/mnt/config/home docker push nephatrine/nginx-ssl:1.18
  - docker rmi pdr.nephatrine.net/nephatrine/nginx-ssl:1.18
- name: build-1.20
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/nginx-ssl:1.20 -f Dockerfile-1.20 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nginx-ssl:1.20
  - docker tag pdr.nephatrine.net/nephatrine/nginx-ssl:1.20 nephatrine/nginx-ssl:1.20
  - HOME=/mnt/config/home docker push nephatrine/nginx-ssl:1.20
  - docker rmi pdr.nephatrine.net/nephatrine/nginx-ssl:1.20
- name: build-latest
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/nginx-ssl:latest .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nginx-ssl:latest
  - docker tag pdr.nephatrine.net/nephatrine/nginx-ssl:latest nephatrine/nginx-ssl:latest
  - HOME=/mnt/config/home docker push nephatrine/nginx-ssl:latest
  - docker rmi pdr.nephatrine.net/nephatrine/nginx-ssl:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: be95fb04b1728166034e694954bb6b41c8c6b57ef030b3f6b83dec38b6780501

...
