---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  environment:
    PDR_USER:
      from_secret: docker-user-pdr
    PDR_PASS:
      from_secret: docker-pass-pdr
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/nginx-ssl:cached --target builder .
  - docker build -t pdr.nephatrine.net/nephatrine/nginx-ssl:latest .
  - docker login -p "$PDR_PASS" -u "$PDR_USER" pdr.nephatrine.net
  - docker push pdr.nephatrine.net/nephatrine/nginx-ssl:latest
  - docker logout pdr.nephatrine.net
- name: publish
  environment:
    DOCKER_USER:
      from_secret: docker-user
    DOCKER_PASS:
      from_secret: docker-pass
  commands:
  - docker tag pdr.nephatrine.net/nephatrine/nginx-ssl:latest nephatrine/nginx-ssl:latest
  - docker tag pdr.nephatrine.net/nephatrine/nginx-ssl:latest nephatrine/nginx-ssl:mainline
  - docker login -p "$DOCKER_PASS" -u "$DOCKER_USER"
  - docker push -a nephatrine/nginx-ssl
  - docker logout
  depends_on:
  - build

---
kind: pipeline
name: notify

steps:
- name: notify-status
  image: appleboy/drone-discord
  failure: ignore
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/nephatrine/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: pipeline
name: propogate

steps:
- name: propogate-downstream
  image: plugins/downstream
  failure: ignore
  settings:
    server: https://ci.nephatrine.net
    token:
      from_secret: drone-auth
    fork: false
    repositories:
    - nephatrine/docker-nginx-php@master
    - nephatrine/docker-quake2@master

depends_on:
- default

---
kind: signature
hmac: 11610c28aabe2dd1d8652be7e5cc0a8a2027659645df555774066e6e5603636a

...
