# SPDX-FileCopyrightText: 2018-2025 Daniel Wolf <nephatrine@gmail.com>
# SPDX-License-Identifier: CC0-1.0

services:
  nginx-ssl:
    build: .
    container_name: nginx-ssl
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /mnt/containers/nginx-ssl:/mnt/config
