#!/usr/bin/with-contenv bash

B_RSA=${B_RSA:-4096}
B_ECDSA=${B_ECDSA:-384}

if [[ ! -d /mnt/config/etc/certbot ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/etc/certbot
fi

if [[ ! -e /mnt/config/etc/certbot/configured ]]; then
  echo "" > /mnt/config/etc/certbot/configured
fi
CURDOMAINS=`head -1 /mnt/config/etc/certbot/configured`
echo "$SSLDOMAINS" > /mnt/config/etc/certbot/requested

if [[ -z "${SSLDOMAINS}" && -z "${CURDOMAINS}" ]]; then
  exit
fi

if [[ ! -d /mnt/config/ssl/live ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/ssl/live
fi

if [[ "x$SSLDOMAINS" != "x$CURDOMAINS" ]]; then
  if [[ $(ls /mnt/config/ssl/live | wc -l) -gt 0 ]]; then
    ls /mnt/config/ssl/live | xargs -n1 -I{} certbot revoke -n --config-dir /mnt/config/ssl --logs-dir /mnt/config/log --max-log-backups 0 --cert-path "/mnt/config/ssl/live/{}/fullchain.pem" --reason superseded --work-dir /tmp/certbot
    ls /mnt/config/ssl/live | xargs -n1 -I{} certbot delete -n --config-dir /mnt/config/ssl --logs-dir /mnt/config/log --max-log-backups 0 --cert-name "{}" --work-dir /tmp/certbot
    rm -rf /mnt/config/etc/certbot/configured
  fi
fi

if [[ $(ls /mnt/config/ssl/live | wc -l) -eq 0 ]]; then
  if [[ ! -z "$SSLDOMAINS" && $SSLEMAIL == *@* ]]; then
    if [[ ${B_ECDSA} -gt 0 ]]; then
      certbot certonly -n --agree-tos --key-type ecdsa --keep --config-dir /mnt/config/ssl --logs-dir /mnt/config/log --max-log-backups 0 --email "$SSLEMAIL" --standalone -d "$SSLDOMAINS" --work-dir /tmp/certbot
    else
      certbot certonly -n --agree-tos --rsa-key-size ${B_RSA} --keep --config-dir /mnt/config/ssl --logs-dir /mnt/config/log --max-log-backups 0 --email "$SSLEMAIL" --standalone -d "$SSLDOMAINS" --work-dir /tmp/certbot
    fi
    if [[ $(ls /mnt/config/ssl/live | wc -l) -gt 0 ]]; then
      cp /mnt/config/etc/certbot/requested /mnt/config/etc/certbot/configured
    fi
  fi
elif [[ ${B_ECDSA} -gt 0 ]]; then
  certbot renew -n --agree-tos --key-type ecdsa --config-dir /mnt/config/ssl --logs-dir /mnt/config/log --max-log-backups 0 --work-dir /tmp/certbot
else
  certbot renew -n --agree-tos --rsa-key-size ${B_RSA} --config-dir /mnt/config/ssl --logs-dir /mnt/config/log --max-log-backups 0 --work-dir /tmp/certbot
fi