#!/usr/bin/with-contenv bash

DNSADDR=${DNSADDR:-"8.8.8.8 8.8.4.4"}
ADMINIP=${ADMINIP:-"127.0.0.1"}
TRUSTSN=${TRUSTSN:-"192.168.0.0/16"}

SSLPRIMARY=`echo $SSLDOMAINS | tr ',' ' ' | awk '{print $1}'`
DOMAINNAME=${SSLPRIMARY:-"example.net"}

THISIP=`ifconfig eth0 | grep 'inet addr' | tr ':' ' ' | awk '{print $3}'`
THISSN=`ifconfig eth0 | grep 'inet addr' | tr ':' ' ' | awk '{print $7}'`
TRSTIP=`ipcalc -n $THISIP $THISSN | tr '=' ' ' | awk '{print $2}'`
TRSTPF=`ipcalc -p $THISIP $THISSN | tr '=' ' ' | awk '{print $2}'`

if [[ ! -f /mnt/config/etc/mime.types ]]; then
  s6-setuidgid guardian cp /etc/nginx/mime.types /mnt/config/etc/mime.types
fi

if [[ ! -f /mnt/config/etc/nginx.conf ]]; then
  s6-setuidgid guardian cp /etc/nginx/nginx.conf /mnt/config/etc/nginx.conf
  sed -i -e "s~8.8.8.8 8.8.4.4~${DNSADDR}~g" /mnt/config/etc/nginx.conf

  if [[ ! -z "${SSLPRIMARY}" ]]; then
    sed -i -e 's/#SSL://g' /mnt/config/etc/nginx.conf
  else
    sed -i -e 's/#SSL:/#/g' /mnt/config/etc/nginx.conf
  fi
fi

if [[ ! -d /mnt/config/etc/nginx.d ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/etc/nginx.d
  s6-setuidgid guardian cp -n /etc/nginx/nginx.d/* /mnt/config/etc/nginx.d/
  grep -rl '127.0.0.1' /mnt/config/etc/nginx.d | xargs -n1 sed -i -e "s/127.0.0.1/${ADMINIP}/g"
  grep -rl 'example.net' /mnt/config/etc/nginx.d | xargs -n1 sed -i -e "s/example.net/${DOMAINNAME}/g"
  grep -rl 'ip_from 192.168.0.0/16' /mnt/config/etc/nginx.d | xargs -n1 sed -i -e "s~ip_from 192.168.0.0/16~ip_from ${TRSTIP}/${TRSTPF}~g"
  grep -rl 'allow 192.168.0.0/16' /mnt/config/etc/nginx.d | xargs -n1 sed -i -e "s~allow 192.168.0.0/16~allow ${TRUSTSN}~g"

  if [[ ! -z "${SSLPRIMARY}" ]]; then
    grep -rl '#NOSSL:' /mnt/config/etc/nginx.d | xargs -n1 sed -i -e 's/#NOSSL:/#/g'
    grep -rl '#SSL:' /mnt/config/etc/nginx.d | xargs -n1 sed -i -e 's/#SSL://g'
  else
    grep -rl '#NOSSL:' /mnt/config/etc/nginx.d | xargs -n1 sed -i -e 's/#NOSSL://g'
    grep -rl '#SSL:' /mnt/config/etc/nginx.d | xargs -n1 sed -i -e 's/#SSL:/#/g'
  fi
fi

if [[ ! -z "${SSLPRIMARY}" ]]; then
  if [[ ! -d /mnt/config/ssl ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/ssl
  fi

  if [[ ! -f /mnt/config/ssl/dhparam.pem ]]; then
    HOME=/mnt/config/home s6-setuidgid guardian openssl dhparam -out /mnt/config/ssl/dhparam.pem 4096
  fi
fi

if [[ ! -d /mnt/config/www ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/www/default
  s6-setuidgid guardian cp -Rn /var/www/html/* /mnt/config/www/default/
fi