#!/usr/bin/with-contenv bash

DNSADDR=${DNSADDR:-"8.8.8.8 8.8.4.4"}
SSLPRIMARY=`echo $SSLDOMAINS | tr ',' ' ' | awk '{print $1}'`

THISIP=`ifconfig eth0 | grep 'inet addr' | tr ':' ' ' | awk '{print $3}'`
THISSN=`ifconfig eth0 | grep 'inet addr' | tr ':' ' ' | awk '{print $7}'`
TRSTIP=`ipcalc -n $THISIP $THISSN | tr '=' ' ' | awk '{print $2}'`
TRSTPF=`ipcalc -p $THISIP $THISSN | tr '=' ' ' | awk '{print $2}'`

if [[ ! -f /mnt/config/etc/mime.types ]]; then
  s6-setuidgid guardian cp /etc/nginx/mime.types /mnt/config/etc/mime.types
fi

if [[ ! -f /mnt/config/etc/nginx.conf ]]; then
  if [[ ! -z "${SSLPRIMARY}" ]]; then
    sed -e "s/8.8.8.8 8.8.4.4/${DNSADDR}/g" /etc/nginx/nginx.conf | sed -e 's/#SSL://g' | sed -e 's/#NOSSL:/#/g' | s6-setuidgid guardian tee /mnt/config/etc/nginx.conf  | grep -v ""
  else
    sed -e "s/8.8.8.8 8.8.4.4/${DNSADDR}/g" /etc/nginx/nginx.conf | sed -e 's/#NOSSL://g' | sed -e 's/#SSL:/#/g' | s6-setuidgid guardian tee /mnt/config/etc/nginx.conf  | grep -v ""
  fi
  if ! grep -q 'REPLACE_WITH_TRUSTED_PROXY_SUBNET' /etc/nginx/nginx.d/default.conf; then
    s6-setuidgid guardian sed -i -e 's/#NOPROXY:/#/g' /mnt/config/etc/nginx.conf
    s6-setuidgid guardian sed -i -e 's/#PROXY://g' /mnt/config/etc/nginx.conf
  else
    s6-setuidgid guardian sed -i -e 's/#NOPROXY://g' /mnt/config/etc/nginx.conf
    s6-setuidgid guardian sed -i -e 's/#PROXY:/#/g' /mnt/config/etc/nginx.conf
  fi
fi

if [[ ! -d /mnt/config/etc/nginx.d ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/etc/nginx.d
  if [[ ! -z "${SSLPRIMARY}" ]]; then
    sed -e "s/REPLACE_WITH_DOMAIN_NAME/${SSLPRIMARY}/g" /etc/nginx/nginx.d/default.conf | sed -e 's/#SSL://g' | sed -e 's/#NOSSL:/#/g' | s6-setuidgid guardian tee /mnt/config/etc/nginx.d/default.conf  | grep -v ""
  else
    sed -e 's/#NOSSL://g' /etc/nginx/nginx.d/default.conf | sed -e 's/#SSL:/#/g' | s6-setuidgid guardian tee /mnt/config/etc/nginx.d/default.conf  | grep -v ""
  fi
  s6-setuidgid guardian sed -i -e "s/REPLACE_WITH_TRUSTED_PROXY_SUBNET/${TRSTIP}\/${TRSTPF}/g" /mnt/config/etc/nginx.d/default.conf
  s6-setuidgid guardian cp -n /etc/nginx/nginx.d/* /mnt/config/etc/nginx.d/
fi

if [[ ! -d /mnt/config/ssl ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/ssl
fi

if [[ ! -z "${SSLPRIMARY}" ]]; then
  if [[ ! -f /mnt/config/ssl/dhparam.pem ]]; then
    s6-setuidgid guardian openssl dhparam -out /mnt/config/ssl/dhparam.pem 4096
  fi
fi

if [[ ! -d /mnt/config/www ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/www/default
  s6-setuidgid guardian cp -n /var/www/html/* /mnt/config/www/default/
fi