#!/bin/bash

B_RSA=${B_RSA:-4096}
B_ECDSA=${B_ECDSA:-384}

if [[ $(ls /mnt/config/ssl/live | wc -l) -gt 0 ]]; then
  if [[ ${B_ECDSA} -gt 0 ]]; then
    certbot renew -n --agree-tos --key-type ecdsa --config-dir /mnt/config/ssl --logs-dir /mnt/config/log --max-log-backups 0 --work-dir /tmp/certbot
  else
    certbot renew -n --agree-tos --rsa-key-size ${B_RSA} --config-dir /mnt/config/ssl --logs-dir /mnt/config/log --max-log-backups 0 --work-dir /tmp/certbot
  fi
fi

exit 0