# SPDX-FileCopyrightText: 2018-2026 Daniel Wolf <nephatrine@gmail.com>
# SPDX-License-Identifier: CC0-1.0

server {
	server_name _;
	#NOSSL:include /mnt/config/etc/nginx.d/_listen_80_default.inc;
	#SSL:include /mnt/config/etc/nginx.d/_listen_443_default.inc;
 	include /mnt/config/etc/nginx.d/_server_common.inc;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

	# You will likely need to tweak this for your particular site.
	#add_header Content-Security-Policy "default-src 'self'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';" always;

	root /mnt/config/www/default;
	include /mnt/config/etc/nginx.d/_server_local.inc;
}

# vim:ft=nginx
