# SPDX-FileCopyrightText: 2018-2026 Daniel Wolf <nephatrine@gmail.com>
# SPDX-License-Identifier: CC0-1.0

#server {
#    server_name subdomain.example.net;
#    #NOSSL:include /mnt/config/etc/nginx.d/_listen_80.inc;
#    #SSL:include /mnt/config/etc/nginx.d/_listen_443.inc;
#    include /mnt/config/etc/nginx.d/_server_common.inc;
#
#    # These will depend greatly on your specific application.
#    #add_header X-Frame-Options "SAMEORIGIN" always;
#    #add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
#    #add_header Content-Security-Policy "frame-ancestors 'self';" always;
#
#    location / {
#        include /mnt/config/etc/nginx.d/_location_proxy.inc;
#        #include /mnt/config/etc/nginx.d/_location_websocket.inc;
#        proxy_pass http://IP:PORT/;
#        #proxy_cache off;
#    }
#}

# vim:ft=nginx
